defaults:
 - mixing_layer: compom
 - _self_
 - gpt: mamba12

vocab_size: 50257
seq_length: ${training.sequence_length}
n_layer: 12
n_head: 24
n_groups: 1
degree: 2
expand: 2
n_embd: 768
hybrid: 4
context_window: 128