# @package _global_

model:
  gpt:
    _target_: models.gpt.Mamba
    mixing_layer: ${model.mixing_layer}
    vocab_size: ${model.vocab_size}
    seq_length: ${model.seq_length}
    n_layer: ${model.n_layer}
    n_head: ${model.n_head}
    n_embd: ${model.n_embd}
    hybrid: ${model.hybrid}
    context_window: ${model.context_window}

